kookouri/ECSE-428-05

- src/main/test/features/003_view_user_profile.feature
Unfortunately I couldn't really come up with an alternative flow or many error flows for viewing profile. As such, I only have the main flow, and one error flow. Feel free to lmk if there's anything else I should add.
> Feature File for View Profile

- src/main/test/features/003_view_user_profile.feature
- Added ID column to table
- Re-arranged table column order
- Adjusted indents to match feature file #4
> Adjusted format of view profile feature file to match feature file #4

- .vscode/settings.json
- McGillMart/McGillMart/build.gradle
- McGillMart/McGillMart/src/main/java/com/controllers/UserController.java
- McGillMart/McGillMart/src/main/java/com/model/Item.java
- McGillMart/McGillMart/src/main/java/com/model/McGillMart.java
- McGillMart/McGillMart/src/main/java/com/model/ShoppingCart.java
- McGillMart/McGillMart/src/main/java/com/model/Transaction.java
- McGillMart/McGillMart/src/main/java/com/model/User.java
- McGillMart/McGillMart/src/main/java/com/repositories/McGillMartRepository.java
- McGillMart/McGillMart/src/main/java/com/repositories/UserRepository.java
- McGillMart/McGillMart/src/main/java/com/services/McGillMartService.java
- McGillMart/McGillMart/src/main/java/com/services/UserService.java
Blockers: Missing UserRequestDTO, UserResponseDTO, UserListDTO
Add McGillMartRepository, McGillMartService
Add package com.model to generated code
> Implement UserController UserService UserRepository

- .gitignore
- McGillMart/McGillMart/build.gradle
- McGillMart/McGillMart/src/main/java/com/controllers/ItemController.java
- McGillMart/McGillMart/src/main/java/com/dto/ItemDTO.java
- McGillMart/McGillMart/src/main/java/com/repositories/ItemRepository.java
- McGillMart/McGillMart/src/main/java/com/services/ItemService.java
- src/main/test/service/ItemServiceTest.java
- src/main/test/stepDefinitions/QueryItemsStepDefinitions.java
- item controller
- item dto
- item dao
- step definitions for querying
- testing querying
> Item management

- McGillMart/McGillMart/src/main/java/com/services/ItemService.java
- McGillMart/McGillMart/src/main/java/com/util/ServiceUtils.java
> Item service

- src/main/test/features/007_review_items.feature
created .feature file for item review
> added item review feature file

- McGillMart/McGillMart/src/main/java/com/services/UserService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/UserServiceTest.java
Created the UserServiceTest.
Added the Create User test
> JUnit tests for create user

- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/UserServiceTest.java
added extra tests if these are going to be implemented in update user: 
- invalid email
- invalid phone number
- invalid password
- empty fields
i added on those extra tests this comment: // not yet implemented in UserService updateUser() method
if these functionality are not going to be added to UserService, i will delete them. Let me know!
> Junit tests for update user

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/LoginController.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/LoginRequestDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/LoginService.java
Hopefully this does everything it needs to
> Create LoginService and LoginController

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ItemController.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ItemDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ReviewDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Item.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/repositories/ReviewRepository.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ReviewService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ReviewServiceTests.java
- McGillMart/McGillMart/src/test/resources/007_review_items.feature
There were some issues with the item codes concerning handling reviews. I added the support for reviews in item classes and created DTO and services and service tests for reviews. All the review tests pass.
> updated code to add reviews to items

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ItemController.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ItemRequestDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ItemResponseDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ReviewRequestDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/ReviewResponseDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/TransactionRequestDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/TransactionResponseDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/UserRequestDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/dto/UserResponseDTO.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Item.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Review.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Transaction.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/User.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ReviewService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ReviewServiceTests.java
Ensure DTOs only contain DTOs
Adjust controllers accordingly
* Unrelated, but change Date to LocalDate to avoid issues in the future with the request and the UI (encountered in 321)
> Create DTO for request and response

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/repositories/ItemRepository.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ItemService.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ReviewService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ItemServiceTests.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ReviewServiceTests.java
> Modified the model, updated services and fixed the tests

- McGillMart/McGillMart-Frontend/src/components/ViewProfile.vue
Minor change; adjusted page style and included Tayba's toolbar in the view profile page
> Adjusted View Profile Page Layout & Style

- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/features/ReviewItemsStepDefinitions.java
added item review step definitions
> added item review step definitions

- McGillMart/McGillMart/src/test/resources/005_view_items.feature
- McGillMart/McGillMart/src/test/resources/006_filter_items.feature
chnages to the float/ item categoties to get rid of the category does not exist error
> chages to the float/ item category spelling

- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/LoginServiceTest.java
> fixing login service test

- McGillMart/McGillMart/src/test/resources/009_add_item_to_cart_list.feature
- Included one main flow, one alternative flow, and one error flow
> Add Item to Cart Feature File (ID009)

- McGillMart/McGillMart-Frontend/src/components/Toolbar.vue
- McGillMart/McGillMart-Frontend/src/components/ViewProfile.vue
- Added a NavBar for Profile; heavily "inspired" from LeJames's page
- Changed the toolbar's hyperlink to redirect to the correct profile page
- NOTE: the view profile page gets info from cookie sessions; have not tested this functionality yet since login has not been implemented
> Added a Navbar for View Profile

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Transaction.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/User.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ShoppingService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ShoppingServiceTests.java
- Add the tests for getting the shopping cart items of a user and getting the transactions(which is the history) of a user
- Changed Transaction controller since its ID is generated and shouldn't be passed into the controller
All tests pass (when the not implemented yet .feature files are removed)
> Tests for viewing the shopping cart and for viewing the transactions (+ getting the shopping cart total)

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/User.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ShoppingService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/features/ViewCartStepDefinitions.java
- McGillMart/McGillMart/src/test/resources/008_view_cart.feature
All view cart tests are now passing.
> View Cart Step Defs

- McGillMart/McGillMart-Frontend/src/components/ItemDisplay.vue
Need to know if this is sufficient for adding an item to the cart
> adding styles

- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/Item.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/model/User.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/repositories/TransactionRepository.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ItemService.java
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/services/ShoppingService.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/features/CheckoutStepDefinitions.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/features/CommonStepDefinitions.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/features/FilterItemsStepDefinitions.java
- McGillMart/McGillMart/src/test/java/com/mcgillmart/McGillMart/service/ItemServiceTests.java
- McGillMart/McGillMart/src/test/resources/011_checking_out.feature
not sure if fully functional if someone can pull and verify. Also did all of the shopping tests
> ShoppingService Tests + checkout functionality + login front end

- McGillMart/McGillMart-Frontend/src/components/OrderHistory.vue
- McGillMart/McGillMart-Frontend/src/components/Review.vue
- McGillMart/McGillMart-Frontend/src/router/index.js
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ItemController.java
issue with creating reviews and seeing reviews of items i think it may be problem with having two requests one for review and one for user
> Frontend review

- McGillMart/McGillMart-Frontend/src/components/Home.vue
- McGillMart/McGillMart-Frontend/src/components/ItemDisplay.vue
- McGillMart/McGillMart-Frontend/src/components/Toolbar.vue
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/DatabaseInitializer.java
> search on the items page (based on category, name or description)

- McGillMart/McGillMart-Frontend/src/components/ItemDisplay.vue
- McGillMart/McGillMart-Frontend/src/components/Review.vue
- McGillMart/McGillMart-Frontend/src/components/Toolbar.vue
- McGillMart/McGillMart/src/main/java/com/mcgillmart/McGillMart/controllers/ItemController.java
fixed issue with other branch about reviews
> fixed review issue
